force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who made the payment</description>
    <inlineHelpText>The person who made the payment</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Amount of payment</description>
    <inlineHelpText>Amount of payment</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Date of payment</description>
    <inlineHelpText>Date of payment</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PaymentsService.cls
public with sharing class PaymentsService {
    
    @AuraEnabled(cacheable=true)
    public static List<Contact> getPeoplePaymentSummaries() {
        
        return [SELECT Id, Name, Total_Payments_Amount__c, Most_Recent_Payment__c 
                FROM Contact
                WHERE Total_Payments_Amount__c != NULL];
    }

    @AuraEnabled(cacheable=true)
    public static List<Payment__c> getPeoplePaymentDetails(Id contactId) {

        return [SELECT Id, Contact__c, Payment_Amount__c, Payment_Date__c 
                FROM Payment__c
                WHERE Contact__c = :contactId
                ORDER BY Payment_Date__c DESC];
    }

    @AuraEnabled
    public static string updateContactList(Object data){
        List<Contact> contactsForUpdate = (List<Contact>) JSON.deserialize(
            JSON.serialize(data),
            List<Contact>.class
        );

        update contactsForUpdate;
        return 'Success: Contacts updated successfully';
    }
}