force-app/main/default/objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Payment__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The person who made the payment</description>
    <inlineHelpText>The person who made the payment</inlineHelpText>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>Payment_Amount__c</fullName>
    <description>Amount of payment</description>
    <inlineHelpText>Amount of payment</inlineHelpText>
    <label>Payment Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Payment_Date__c.field-meta.xml
<CustomField>
    <fullName>Payment_Date__c</fullName>
    <description>Date of payment</description>
    <inlineHelpText>Date of payment</inlineHelpText>
    <label>Payment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Payment__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The project to which payment was made</description>
    <inlineHelpText>The project to which payment was made</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Total_Payments_Amount__c.field-meta.xml
<CustomField>
    <fullName>Total_Payments_Amount__c</fullName>
    <description>Total amount of payments made to this project</description>
    <inlineHelpText>Total amount of payments made to this project</inlineHelpText>
    <label>Total Payments Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PaymentTriggerHandler.cls
public class PaymentTriggerHandler {
    public void UpdateProjectsAndContacts(List<Payment__c> payments){
        
        UpdateProjects(payments);
        UpdateContacts(payments);
 
    }
    
    public void UpdateProjects(List<Payment__c> payments){
        
        // restrict updates to only those projects appearing in these payments
        Set<ID> projectIds = new Set<ID>();
        for(Payment__c payment : payments){
            projectIds.add(payment.Project__c);
        }
        
        // get all payments related to the above projects
        Map<Id, Project__c> projectMap = new Map<Id, Project__c>(
            [SELECT Id, Total_Payments_Amount__c FROM Project__c WHERE Id in :projectIds]);
        
        // calculate total payments by Project
        AggregateResult[] groupedResults = [SELECT Project__c, SUM(Payment_Amount__c) Total_Payments
                                            FROM Payment__c
                                            WHERE Project__c in :projectIds
                                            GROUP BY Project__c];
        
        // Update Projects with new total payments
        for (AggregateResult ar : groupedResults)  {
            Id projectId = (Id)ar.get('Project__c'); // get projectId from aggregate result
            Project__c project = projectMap.get(projectId); // get project record from Map
            project.Total_Payments_Amount__c = (Decimal)ar.get('Total_Payments');
        }
        update projectMap.values();
    }
    
    
    public void UpdateContacts(List<Payment__c> payments){
        
        // restrict updates to only those Contacts appearing in these payments
        Set<ID> contactIds = new Set<ID>();
        for(Payment__c payment : payments){
            contactIds.add(payment.Contact__c);
        }
        
        // get all payments related to the above Contacts
        Map<Id, Contact> contactMap = new Map<Id, Contact>(
            [SELECT Id, Total_Payments_Amount__c FROM Contact WHERE Id in :contactIds]);
        
        // calculate total payments by Contact
        AggregateResult[] groupedResults = [SELECT Contact__c, 
                                            SUM(Payment_Amount__c) Total_Payments,
                                            MAX(Payment_Date__c) Most_Recent_Payment
                                            FROM Payment__c
                                            WHERE Contact__c in :contactIds
                                            GROUP BY Contact__c];
        
        // Update Projects with new total payments
        for (AggregateResult ar : groupedResults)  {
            Id contactId = (Id)ar.get('Contact__c');
            Contact contact = contactMap.get(contactId);
            contact.Total_Payments_Amount__c = (Decimal)ar.get('Total_Payments');
            contact.Most_Recent_Payment__c = (Date)ar.get('Most_Recent_Payment');
        }
        update contactMap.values();
    }
}